// <auto-generated />
using AssistantEngineer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistantEngineer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistantEngineer.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaM2")
                        .HasColumnType("double precision");

                    b.Property<double>("EquipmentLoadW")
                        .HasColumnType("double precision");

                    b.Property<double>("HeightM")
                        .HasColumnType("double precision");

                    b.Property<double>("IndoorTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double>("LightingLoadW")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OutdoorTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<double>("VolumeM3")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("AssistantEngineer.Models.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaM2")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("AssistantEngineer.Models.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaM2")
                        .HasColumnType("double precision");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Windows");
                });

            modelBuilder.Entity("AssistantEngineer.Models.Wall", b =>
                {
                    b.HasOne("AssistantEngineer.Models.Room", "Room")
                        .WithMany("Walls")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AssistantEngineer.Models.Window", b =>
                {
                    b.HasOne("AssistantEngineer.Models.Room", "Room")
                        .WithMany("Windows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AssistantEngineer.Models.Room", b =>
                {
                    b.Navigation("Walls");

                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
