namespace AssistantEngineer.Tests.Parity.EnergyCalculationParity.FormulaAudit;

public static class FormulaAuditMatrix
{
    public static IReadOnlyList<FormulaAuditFeature> Features { get; } =
    [
        new(
            CalculationId: "HVAC.TRANSMISSION.SIMPLE_UA",
            Name: "Transmission heat transfer",
            Formula: "Q = U * A * ΔT * correctionFactor",
            Units: "W = W/(m²·K) * m² * K * dimensionless",
            SourcePrinciple: "ISO/engineering steady-state envelope heat transfer principle; pyBuildingEnergy/ISO52016-inspired component input.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Transmission",
            Diagnostics: "Boundary type, internal adiabatic surface, ground boundary warning, invalid input diagnostics.",
            Tests: "Transmission deterministic fixtures and engine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Component steady-state engineering formula; does not claim full dynamic ISO 52016 node/matrix heat-balance parity."),

        new(
            CalculationId: "HVAC.VENTILATION.SENSIBLE_AIRFLOW",
            Name: "Ventilation and infiltration sensible load",
            Formula: "Q = ρ * cp * Vdot * ΔT",
            Units: "W = kg/m³ * J/(kg·K) * m³/s * K",
            SourcePrinciple: "Sensible air heat capacity method used by HVAC engineering calculations and ISO-style heat-balance inputs.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Ventilation",
            Diagnostics: "Airflow normalization, ACH conversion, heat recovery, invalid efficiency and fallback assumptions.",
            Tests: "Ventilation/infiltration deterministic fixtures and engine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Sensible-only v1 model; latent load and moisture balance are intentionally out of scope."),

        new(
            CalculationId: "HVAC.INTERNAL_GAINS.SENSIBLE",
            Name: "Internal sensible gains",
            Formula: "Qinternal = Qpeople,sensible + Qlighting + Qequipment + Qprocess + Qcustom",
            Units: "W = W + W + W + W + W",
            SourcePrinciple: "ISO52016/engineering internal heat gain decomposition; pyBuildingEnergy-inspired sensible gains input.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.InternalGains",
            Diagnostics: "Schedule factor, occupancy gains, lighting density, equipment density, process/custom gains and invalid input diagnostics.",
            Tests: "Internal gains deterministic fixtures and engine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Latent gains may be calculated separately as diagnostics/data, but latent HVAC energy path is not part of v1."),

        new(
            CalculationId: "HVAC.WINDOW_SOLAR.SIMPLE_SHGC",
            Name: "Window solar gains",
            Formula: "Qsolar = Iincident * Awindow * SHGC * frameFactor * internalShading * externalShading * fixedShading",
            Units: "W = W/m² * m² * dimensionless factors",
            SourcePrinciple: "Solar gain through transparent elements using SHGC and shading factors; ISO52010/ISO52016-inspired input.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.SolarGains",
            Diagnostics: "Incident irradiance source, SHGC validation, frame/shading factors, night-zero solar diagnostics.",
            Tests: "Window solar gain deterministic fixtures, benchmark fixtures and night-zero tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Simplified engineering window solar model; does not claim full optical glazing or EnergyPlus solar distribution parity."),

        new(
            CalculationId: "HVAC.SOLAR.SURFACE_IRRADIANCE_ISOTROPIC",
            Name: "Solar position and isotropic surface irradiance",
            Formula: "Itotal = DNI * max(cosθ, 0) + DHI * (1 + cosβ) / 2 + GHI * albedo * (1 - cosβ) / 2",
            Units: "W/m² = W/m² + W/m² + W/m²",
            SourcePrinciple: "ISO52010-inspired solar geometry and isotropic sky transposition.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Solar",
            Diagnostics: "Solar altitude/azimuth, incidence angle, direct/diffuse/ground-reflected components, night-zero behavior.",
            Tests: "Surface irradiance deterministic fixtures and solar night-zero tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Uses isotropic sky model for v1; does not claim anisotropic/Perez sky or EnergyPlus solar transposition parity."),

        new(
            CalculationId: "HVAC.ROOM_LOAD.DESIGN_POINT",
            Name: "Room design-point heating and cooling load",
            Formula: "Qheating = transmission + windowTransmission + ground + ventilation + infiltration; Qcooling = transmission + windowTransmission + ground + ventilation + infiltration + solar + internalGains",
            Units: "W = sum of W components",
            SourcePrinciple: "HVAC engineering design-point load decomposition; uses ISO-style component categories but not full hourly dynamic balance.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.RoomLoads",
            Diagnostics: "Component breakdown, requested/actual method, fallback assumptions and non-negative load handling.",
            Tests: "Room load deterministic fixtures and application pipeline tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Design-point load calculation; does not claim full ISO 52016 hourly dynamic zone solver parity."),

        new(
            CalculationId: "HVAC.AGGREGATION.LOAD_SUMMARY",
            Name: "Room, thermal zone, floor and building load aggregation",
            Formula: "Qtarget = Σ Qroom; hourly mode uses coincident hourly peak when profiles are available",
            Units: "W = sum of W room loads",
            SourcePrinciple: "Engineering load aggregation with optional coincident hourly peak.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Aggregation",
            Diagnostics: "No rooms warning, hourly unavailable fallback warning, invalid room area validation, component summary.",
            Tests: "Aggregation deterministic fixtures and LoadAggregationEngine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Aggregation layer; does not claim coupled multi-zone heat-transfer solver parity."),

        new(
            CalculationId: "HVAC.ANNUAL_ENERGY.HOURLY_KWH",
            Name: "Annual and monthly energy balance from hourly records",
            Formula: "E = Σ(Qhour * Δthour) / 1000; Eannual = Σ Emonth; EUI = Eannual / area",
            Units: "kWh = W * h / 1000; kWh/m² = kWh / m²",
            SourcePrinciple: "Hourly-to-monthly and hourly-to-annual energy integration used by ISO-style annual calculations.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.AnnualEnergy",
            Diagnostics: "TrueHourlySimulation source, 8760 record count, monthly adapter warning, synthetic weather warning, signed component balance.",
            Tests: "Annual energy deterministic fixtures, benchmark fixtures, AnnualEnergyBalanceEngine tests and explicit end-to-end true hourly 8760 scenario.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Closed as hourly energy integration gate for engineering-core v1; does not claim full ISO 52016 node/matrix solver or EnergyPlus parity."),

        new(
            CalculationId: "WEATHER.EPW_8760",
            Name: "EPW hourly weather import and normalization",
            Formula: "EPW hourly rows -> normalized 8760 annual weather profile",
            Units: "Hourly dry-bulb °C, RH %, pressure Pa/kPa, wind m/s, DNI/DHI/GHI W/m²",
            SourcePrinciple: "Weather-driven hourly simulation input; pyBuildingEnergy supports EPW-style weather workflows.",
            ImplementationArea: "AssistantEngineer.Modules.Buildings.Application.Services.Climate.EpwAnnualClimateDataImportService",
            Diagnostics: "Header parsing, leap day handling, missing/invalid radiation and 8760 record count diagnostics.",
            Tests: "EPW importer tests assert 8760 output, leap-year normalization, short-file rejection and radiation normalization.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Closed as weather normalization gate for engineering-core v1; does not claim external EPW provider accuracy validation."),

        new(
            CalculationId: "WEATHER.PVGIS_8760",
            Name: "PVGIS TMY hourly weather import and normalization",
            Formula: "PVGIS TMY hourly rows -> normalized 8760 annual weather profile",
            Units: "Hourly T2m °C, RH %, pressure, wind m/s, DNI/DHI/GHI or equivalent solar fields W/m²",
            SourcePrinciple: "Weather-driven hourly simulation input; pyBuildingEnergy supports PVGIS weather workflows.",
            ImplementationArea: "AssistantEngineer.Modules.Buildings.Application.Services.Climate.PvgisAnnualClimateDataImportService",
            Diagnostics: "PVGIS source metadata, hourly ordering, missing solar fields and 8760 record count diagnostics.",
            Tests: "PVGIS importer tests assert 8760 output, Jan-Dec ordering, short-profile rejection, solar mapping and optional-field normalization.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Closed as weather normalization gate for engineering-core v1; does not claim external PVGIS service accuracy validation."),

        new(
            CalculationId: "HVAC.DHW.SIMPLIFIED",
            Name: "Simplified domestic hot water demand",
            Formula: "Edhw = V * ρwater * cp,water * ΔT + distributionLosses + storageLosses + circulationLosses",
            Units: "kWh = kg * kJ/(kg·K) * K / 3600 + kWh losses",
            SourcePrinciple: "Simplified DHW energy demand based on water volume and temperature lift; EN12831-3-inspired scope.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Dhw",
            Diagnostics: "Occupancy, liters per person, cold/hot water temperature, losses and zero occupancy diagnostics.",
            Tests: "DHW deterministic fixtures and DHW engine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P1,
            Limitations: "Simplified DHW demand; does not claim full EN 12831-3 tapping profile or distribution system parity."),

        new(
            CalculationId: "HVAC.SYSTEM_ENERGY.SIMPLIFIED",
            Name: "Simplified system final and primary energy",
            Formula: "Final = Useful / efficiency or Useful / COP; Primary = Final * primaryEnergyFactor",
            Units: "kWh = kWh / dimensionless; kWhprimary = kWhfinal * factor",
            SourcePrinciple: "Simplified final/primary energy conversion; EN15316-inspired reporting scope.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.SystemEnergy",
            Diagnostics: "Missing efficiency/COP warning, invalid efficiency/COP validation, primary factor diagnostics.",
            Tests: "System energy deterministic fixtures and SystemEnergyEngine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P1,
            Limitations: "Simplified system energy model; does not claim full EN 15316 generation/distribution/storage/emission chain."),

        new(
            CalculationId: "HVAC.EQUIPMENT_SIZING.CAPACITY_MARGIN",
            Name: "Equipment sizing by required load and capacity margin",
            Formula: "Required = Load * safetyFactor; Margin = Capacity - Required; Margin% = Margin / Required * 100",
            Units: "W = W * dimensionless; % = W / W * 100",
            SourcePrinciple: "Engineering equipment sizing by capacity reserve and deterministic candidate ranking.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.EquipmentSizing",
            Diagnostics: "Safety factor defaults, invalid load validation, empty candidate warning, no recommended equipment warning.",
            Tests: "Equipment sizing deterministic fixtures and EquipmentSizingEngine tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P1,
            Limitations: "Capacity sizing only; does not claim part-load performance, manufacturer curves or detailed HVAC plant operation."),

        new(
            CalculationId: "HVAC.GROUND.SIMPLIFIED",
            Name: "Simplified ground heat transfer",
            Formula: "Hground = Ueq * Area; Qground = Hground * ΔT",
            Units: "W = W/K * K; W/K = W/(m²·K) * m²",
            SourcePrinciple: "ISO13370-inspired ground coupling using equivalent U/H values and engineering metadata.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Ground",
            Diagnostics: "Ground contact type, characteristic dimension, perimeter/burial/insulation factors and fallback warnings.",
            Tests: "Ground deterministic tests and ground preview/service tests.",
            Status: FormulaAuditStatus.Partial,
            Priority: FormulaAuditPriority.P1,
            Limitations: "ISO13370-inspired simplified model; does not claim full ISO 13370 implementation."),

        new(
            CalculationId: "HVAC.HOURLY_HEAT_BALANCE.SIMPLIFIED_RC",
            Name: "Simplified hourly heat balance / free-floating temperature",
            Formula: "Tfree ≈ Teq + (Tprev - Teq) * exp(-H * Δt / C) or equivalent quasi-implicit RC balance",
            Units: "°C from W/K, Wh/K, W gains/losses and hourly timestep",
            SourcePrinciple: "ISO52016-inspired hourly zone heat-balance concept; simplified RC engineering approximation.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Iso52016",
            Diagnostics: "Heating/cooling setpoint behavior, free-floating temperature, component heat balance and hourly source diagnostics.",
            Tests: "Single-zone deterministic fixtures, ISO52016-inspired contract tests and explicit end-to-end 8760 simplified hourly heat-balance scenario.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Closed as simplified hourly heat-balance gate for engineering-core v1; does not claim full ISO 52016 node/matrix solver parity."),

        new(
            CalculationId: "HVAC.THERMAL_ZONE.SINGLE_ZONE",
            Name: "Single thermal zone calculation path",
            Formula: "Zone load/profile = aggregation and/or hourly balance over rooms assigned to one thermal zone",
            Units: "W and kWh by zone",
            SourcePrinciple: "Thermal zone as core ISO52016/pyBuildingEnergy calculation concept.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.ThermalZones and Aggregation",
            Diagnostics: "Zone aggregation, assigned room count, no double-counting, hourly fallback and method diagnostics.",
            Tests: "Thermal zone aggregation fixtures, single-zone fixtures and explicit assigned-room-only aggregation tests.",
            Status: FormulaAuditStatus.ClosedV1,
            Priority: FormulaAuditPriority.P0,
            Limitations: "Closed as single-zone engineering path for v1; does not claim coupled multi-zone heat exchange parity."),

        new(
            CalculationId: "HVAC.ADJACENT_ZONE.SIMPLIFIED",
            Name: "Simplified adjacent zone boundary handling",
            Formula: "Qadjacent = U * A * (Tzone - Tadjacent) * correctionFactor",
            Units: "W = W/(m²·K) * m² * K * dimensionless",
            SourcePrinciple: "Engineering adjacent boundary heat-transfer treatment inspired by ISO zone boundary concepts.",
            ImplementationArea: "AssistantEngineer.Modules.Calculations.Application.Services.Transmission and Iso52016 adjacent-zone helpers",
            Diagnostics: "Adjacent conditioned/unconditioned boundary diagnostics and fallback temperature assumptions.",
            Tests: "Adjacent conditioned transmission fixtures and planned adjacent-zone hourly tests.",
            Status: FormulaAuditStatus.Partial,
            Priority: FormulaAuditPriority.P1,
            Limitations: "Simplified adjacent boundary model; does not claim coupled multi-zone solver parity."),

        new(
            CalculationId: "HVAC.LATENT_LOAD",
            Name: "Latent load calculation",
            Formula: "Not implemented in v1",
            Units: "Not applicable",
            SourcePrinciple: "Psychrometric HVAC latent load calculation; intentionally excluded from engineering-core v1.",
            ImplementationArea: "Not implemented",
            Diagnostics: "Out of scope marker only.",
            Tests: "Out-of-scope guard tests.",
            Status: FormulaAuditStatus.OutOfScopeV1,
            Priority: FormulaAuditPriority.P3,
            Limitations: "Future psychrometrics module; not required for sensible heating/cooling v1."),

        new(
            CalculationId: "HVAC.MOISTURE_BALANCE",
            Name: "Moisture balance and humidification/dehumidification",
            Formula: "Not implemented in v1",
            Units: "Not applicable",
            SourcePrinciple: "Moisture balance and supply-air humidity conditions; intentionally excluded from engineering-core v1.",
            ImplementationArea: "Not implemented",
            Diagnostics: "Out of scope marker only.",
            Tests: "Out-of-scope guard tests.",
            Status: FormulaAuditStatus.OutOfScopeV1,
            Priority: FormulaAuditPriority.P3,
            Limitations: "Future psychrometrics/HVAC air treatment module; not required for sensible heating/cooling v1."),

        new(
            CalculationId: "VALIDATION.ENERGYPLUS_ASHRAE140",
            Name: "Future EnergyPlus / ASHRAE 140 validation layer",
            Formula: "Comparative validation cases, not production formula",
            Units: "Case-dependent W, kWh and temperature comparisons",
            SourcePrinciple: "Future engineering validation against EnergyPlus/simple ASHRAE 140-style cases.",
            ImplementationArea: "tests/AssistantEngineer.Tests/Validation/EnergyPlus or future benchmarks module",
            Diagnostics: "Validation-only reporting, tolerances and case metadata.",
            Tests: "Planned validation fixtures.",
            Status: FormulaAuditStatus.PlannedValidation,
            Priority: FormulaAuditPriority.P2,
            Limitations: "Not required to close formula implementation v1; must not be used as exact watt-by-watt parity claim.")
    ];
}