using System.Globalization;
using AssistantEngineer.Application.Abstractions;
using AssistantEngineer.Application.Abstractions.Repositories;
using AssistantEngineer.Application.Contracts.Requests;
using AssistantEngineer.Application.Services.Climate;
using AssistantEngineer.Domain.Models;
using AssistantEngineer.Domain.Models.Climate;
using AssistantEngineer.Domain.Primitives;
using AssistantEngineer.Domain.ValueObjects;

namespace AssistantEngineer.Tests;

public class EpwWeatherImportServiceTests
{
    [Fact]
    public async Task ImportAsyncStoresAnnualClimateDataFromEpw()
    {
        var tempDirectory = CreateTempDirectory();
        try
        {
            var epwPath = Path.Combine(tempDirectory, "weather.epw");
            await File.WriteAllTextAsync(epwPath, CreateEpwContent());
            var climateZone = ClimateZone.Create(
                "Imported climate",
                Temperature.FromCelsius(35).Value,
                Temperature.FromCelsius(-10).Value).Value;
            var annualRepository = new AnnualClimateDataRepositoryStub();
            var context = new AppDbContextStub();
            var service = new EpwWeatherImportService(
                new ClimateZoneRepositoryStub(climateZone),
                annualRepository,
                context);

            var result = await service.ImportAsync(
                climateZone.Id,
                new ImportEpwWeatherRequest { FilePath = epwPath, Year = 2020 });

            Assert.True(result.IsSuccess, result.Error);
            Assert.Equal(8760, result.Value.HourlyRecordsImported);
            Assert.Equal(1, context.SaveChangesCallCount);
            Assert.NotNull(annualRepository.StoredAnnualData);
            Assert.Equal(8760, annualRepository.StoredAnnualData.HourlyData.Count);
            Assert.Equal(15, annualRepository.StoredAnnualData.HourlyData.First().DryBulbTemperature);
            Assert.Equal(100, annualRepository.StoredAnnualData.HourlyData.First().DirectSolarRadiation);
            Assert.Equal(20, annualRepository.StoredAnnualData.HourlyData.First().DiffuseSolarRadiation);
            Assert.Equal(50, annualRepository.StoredAnnualData.HourlyData.First().RelativeHumidityPercent);
            Assert.Equal(101325, annualRepository.StoredAnnualData.HourlyData.First().AtmosphericPressurePa);
            Assert.Equal(3.2, annualRepository.StoredAnnualData.HourlyData.First().WindSpeedMPerS);
            Assert.Equal(180, annualRepository.StoredAnnualData.HourlyData.First().WindDirectionDegrees);
            Assert.Equal(320, annualRepository.StoredAnnualData.HourlyData.First().HorizontalInfraredRadiationWPerM2);
            Assert.NotNull(annualRepository.StoredAnnualData.HourlyData.First().SkyTemperatureC);
            Assert.Equal(4, annualRepository.StoredAnnualData.HourlyData.First().TotalSkyCoverTenths);
            Assert.Equal(2, annualRepository.StoredAnnualData.HourlyData.First().OpaqueSkyCoverTenths);
            Assert.Contains("WindSpeed", result.Value.ImportedFields);
        }
        finally
        {
            Directory.Delete(tempDirectory, recursive: true);
        }
    }

    [Fact]
    public async Task ImportAsyncReturnsNotFoundWhenEpwFileDoesNotExist()
    {
        var climateZone = ClimateZone.Create(
            "Imported climate",
            Temperature.FromCelsius(35).Value,
            Temperature.FromCelsius(-10).Value).Value;
        var service = new EpwWeatherImportService(
            new ClimateZoneRepositoryStub(climateZone),
            new AnnualClimateDataRepositoryStub(),
            new AppDbContextStub());

        var result = await service.ImportAsync(
            climateZone.Id,
            new ImportEpwWeatherRequest { FilePath = "missing.epw", Year = 2020 });

        Assert.True(result.IsFailure);
        Assert.Equal(ResultErrorType.NotFound, result.ErrorType);
    }

    private static string CreateEpwContent()
    {
        var lines = new List<string>
        {
            "LOCATION,Test,Test,USA,TMY,000000,0,0,0,0",
            "DESIGN CONDITIONS,0",
            "TYPICAL/EXTREME PERIODS,0",
            "GROUND TEMPERATURES,0",
            "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
            "COMMENTS 1,Generated by tests",
            "COMMENTS 2,Generated by tests",
            "DATA PERIODS,1,1,Data,Sunday,1/1,12/31"
        };

        var start = new DateTime(2021, 1, 1);
        for (var hour = 0; hour < 8760; hour++)
        {
            var timestamp = start.AddHours(hour);
            lines.Add(CreateEpwDataLine(timestamp));
        }

        return string.Join(Environment.NewLine, lines);
    }

    private static string CreateEpwDataLine(DateTime timestamp)
    {
        var fields = new string[35];
        Array.Fill(fields, "0");
        fields[0] = timestamp.Year.ToString(CultureInfo.InvariantCulture);
        fields[1] = timestamp.Month.ToString(CultureInfo.InvariantCulture);
        fields[2] = timestamp.Day.ToString(CultureInfo.InvariantCulture);
        fields[3] = (timestamp.Hour + 1).ToString(CultureInfo.InvariantCulture);
        fields[4] = "60";
        fields[5] = "?9?9?9?9";
        fields[6] = "15";
        fields[7] = "10";
        fields[8] = "50";
        fields[9] = "101325";
        fields[12] = "320";
        fields[13] = "120";
        fields[14] = "100";
        fields[15] = "20";
        fields[20] = "180";
        fields[21] = "3.2";
        fields[22] = "4";
        fields[23] = "2";
        return string.Join(",", fields);
    }

    private static string CreateTempDirectory()
    {
        var path = Path.Combine(Path.GetTempPath(), $"assistant-engineer-epw-tests-{Guid.NewGuid():N}");
        Directory.CreateDirectory(path);
        return path;
    }

    private sealed class ClimateZoneRepositoryStub : IClimateZoneRepository
    {
        private readonly ClimateZone _climateZone;

        public ClimateZoneRepositoryStub(ClimateZone climateZone)
        {
            _climateZone = climateZone;
        }

        public Task<ClimateZone?> GetByIdAsync(
            int id,
            CancellationToken cancellationToken = default) =>
            Task.FromResult<ClimateZone?>(id == _climateZone.Id ? _climateZone : null);
    }

    private sealed class AnnualClimateDataRepositoryStub : IAnnualClimateDataRepository
    {
        public AnnualClimateData? StoredAnnualData { get; private set; }

        public Task<AnnualClimateData?> GetForClimateZoneAsync(
            int climateZoneId,
            int year,
            CancellationToken cancellationToken = default) =>
            Task.FromResult<AnnualClimateData?>(StoredAnnualData);

        public Task ReplaceForClimateZoneAsync(
            AnnualClimateData annualClimateData,
            CancellationToken cancellationToken = default)
        {
            StoredAnnualData = annualClimateData;
            return Task.CompletedTask;
        }
    }

    private sealed class AppDbContextStub : IAppDbContext
    {
        public int SaveChangesCallCount { get; private set; }

        public Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            SaveChangesCallCount++;
            return Task.FromResult(1);
        }
    }
}
