// <auto-generated />
using AssistantEngineer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistantEngineer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418181228_AddUniqueIndexes")]
    partial class AddUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistantEngineer.Domain.Equipment.CoolingEquipmentCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "SystemType", "UnitType", "ModelName")
                        .IsUnique()
                        .HasDatabaseName("IX_EquipmentCatalogItems_CatalogIdentity");

                    b.ToTable("EquipmentCatalogItems", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.CalculationPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CoolingSafetyFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatingSafetyFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CalculationPreferences", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.ClimateZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ClimateZones", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "Name")
                        .IsUnique();

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<double>("HeightM")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Walls", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Windows", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Equipment.CoolingEquipmentCatalogItem", b =>
                {
                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Power", "NominalCoolingCapacity", b1 =>
                        {
                            b1.Property<int>("CoolingEquipmentCatalogItemId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("NominalCoolingCapacityW");

                            b1.HasKey("CoolingEquipmentCatalogItemId");

                            b1.ToTable("EquipmentCatalogItems");

                            b1.WithOwner()
                                .HasForeignKey("CoolingEquipmentCatalogItemId");
                        });

                    b.Navigation("NominalCoolingCapacity")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Building", b =>
                {
                    b.HasOne("AssistantEngineer.Domain.Models.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Domain.Models.Project", "Project")
                        .WithMany("Buildings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateZone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.CalculationPreferences", b =>
                {
                    b.HasOne("AssistantEngineer.Domain.Models.Project", "Project")
                        .WithOne("Preferences")
                        .HasForeignKey("AssistantEngineer.Domain.Models.CalculationPreferences", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.ClimateZone", b =>
                {
                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Temperature", "SummerDesignTemperature", b1 =>
                        {
                            b1.Property<int>("ClimateZoneId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("SummerDesignTemperatureC");

                            b1.HasKey("ClimateZoneId");

                            b1.ToTable("ClimateZones");

                            b1.WithOwner()
                                .HasForeignKey("ClimateZoneId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Temperature", "WinterDesignTemperature", b1 =>
                        {
                            b1.Property<int>("ClimateZoneId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("WinterDesignTemperatureC");

                            b1.HasKey("ClimateZoneId");

                            b1.ToTable("ClimateZones");

                            b1.WithOwner()
                                .HasForeignKey("ClimateZoneId");
                        });

                    b.Navigation("SummerDesignTemperature")
                        .IsRequired();

                    b.Navigation("WinterDesignTemperature")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Floor", b =>
                {
                    b.HasOne("AssistantEngineer.Domain.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Room", b =>
                {
                    b.HasOne("AssistantEngineer.Domain.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Power", "EquipmentLoad", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("EquipmentLoadW");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Temperature", "IndoorTemperature", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("IndoorTemperatureC");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Power", "LightingLoad", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("LightingLoadW");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Temperature", "OutdoorTemperature", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("OutdoorTemperatureC");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("EquipmentLoad")
                        .IsRequired();

                    b.Navigation("Floor");

                    b.Navigation("IndoorTemperature")
                        .IsRequired();

                    b.Navigation("LightingLoad")
                        .IsRequired();

                    b.Navigation("OutdoorTemperature")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Wall", b =>
                {
                    b.HasOne("AssistantEngineer.Domain.Models.Room", "Room")
                        .WithMany("Walls")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("WallId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.ThermalTransmittance", "UValue", b1 =>
                        {
                            b1.Property<int>("WallId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("UValue");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("UValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Window", b =>
                {
                    b.HasOne("AssistantEngineer.Domain.Models.Room", "Room")
                        .WithMany("Windows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.ThermalTransmittance", "UValue", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("UValue");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.Domain.ValueObjects.SolarHeatGainCoefficient", "Shgc", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("SHGC");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Shgc")
                        .IsRequired();

                    b.Navigation("UValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Project", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("AssistantEngineer.Domain.Models.Room", b =>
                {
                    b.Navigation("Walls");

                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
