// <auto-generated />
using AssistantEngineer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistantEngineer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429013955_AddRoomGroundContactMetadata")]
    partial class AddRoomGroundContactMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId", "Year")
                        .IsUnique();

                    b.ToTable("AnnualClimateData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<double>("DailyTemperatureRange")
                        .HasColumnType("double precision");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId", "Month")
                        .IsUnique();

                    b.ToTable("ClimateData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ClimateZones", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.HourlyClimateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnnualClimateDataId")
                        .HasColumnType("integer");

                    b.Property<double?>("AtmosphericPressurePa")
                        .HasColumnType("double precision");

                    b.Property<int?>("ClimateDataId")
                        .HasColumnType("integer");

                    b.Property<double>("DiffuseSolarRadiation")
                        .HasColumnType("double precision");

                    b.Property<double>("DirectSolarRadiation")
                        .HasColumnType("double precision");

                    b.Property<double>("DryBulbTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("HorizontalInfraredRadiationWPerM2")
                        .HasColumnType("double precision");

                    b.Property<int?>("Hour")
                        .HasColumnType("integer");

                    b.Property<int?>("HourOfYear")
                        .HasColumnType("integer");

                    b.Property<double?>("OpaqueSkyCoverTenths")
                        .HasColumnType("double precision");

                    b.Property<double?>("RelativeHumidityPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("SkyTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalSkyCoverTenths")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindDirectionDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMPerS")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnnualClimateDataId", "HourOfYear")
                        .IsUnique()
                        .HasFilter("\"AnnualClimateDataId\" IS NOT NULL AND \"HourOfYear\" IS NOT NULL");

                    b.HasIndex("ClimateDataId", "Hour")
                        .IsUnique()
                        .HasFilter("\"ClimateDataId\" IS NOT NULL AND \"Hour\" IS NOT NULL");

                    b.ToTable("HourlyClimateData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ConstructionAssemblies", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionAssemblyId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<double>("ThicknessM")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionAssemblyId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ConstructionLayers", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DensityKgPerM3")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("SpecificHeatJPerKgK")
                        .HasColumnType("double precision");

                    b.Property<double>("ThermalConductivityWPerMK")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "Name")
                        .IsUnique();

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<double>("HeightM")
                        .HasColumnType("double precision");

                    b.Property<int?>("LightingScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OccupancyScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VentilationParametersId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentScheduleId");

                    b.HasIndex("LightingScheduleId");

                    b.HasIndex("OccupancyScheduleId");

                    b.HasIndex("VentilationParametersId");

                    b.HasIndex("FloorId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdjacentRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("BoundaryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ConstructionAssemblyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdjacentRoomId");

                    b.HasIndex("ConstructionAssemblyId");

                    b.HasIndex("RoomId");

                    b.ToTable("Walls", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Windows", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Factors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("HourlySchedules", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Settings.CalculationPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CoolingSafetyFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatingSafetyFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("Iso52016DefaultAirChangesPerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5);

                    b.Property<double>("Iso52016DiffuseSolarShareUnaffectedByShading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("Iso52016DirectSolarShadingReductionFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<double>("Iso52016InternalHeatCapacityJPerM2K")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(10000.0);

                    b.Property<double>("Iso52016SolarUtilizationFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.75);

                    b.Property<double>("Iso52016WindowFrameAreaFraction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.25);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CalculationPreferences", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.ThermalZones.ThermalZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("ThermalZones", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Ventilation.VentilationParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AirChangesPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatRecoveryEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("InfiltrationAirChangesPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("StackCoefficient")
                        .HasColumnType("double precision");

                    b.Property<double>("WindCoefficient")
                        .HasColumnType("double precision");

                    b.Property<double>("WindExposureFactor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("VentilationParameters", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Equipment.Domain.CoolingEquipmentCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "SystemType", "UnitType", "ModelName")
                        .IsUnique()
                        .HasDatabaseName("IX_EquipmentCatalogItems_CatalogIdentity");

                    b.ToTable("EquipmentCatalogItems", (string)null);
                });

            modelBuilder.Entity("ThermalZoneRooms", b =>
                {
                    b.Property<int>("ThermalZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("ThermalZoneId", "RoomId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("ThermalZoneRooms", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClimateZone");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClimateZone");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", b =>
                {
                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "SummerDesignTemperature", b1 =>
                        {
                            b1.Property<int>("ClimateZoneId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("SummerDesignTemperatureC");

                            b1.HasKey("ClimateZoneId");

                            b1.ToTable("ClimateZones");

                            b1.WithOwner()
                                .HasForeignKey("ClimateZoneId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "WinterDesignTemperature", b1 =>
                        {
                            b1.Property<int>("ClimateZoneId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("WinterDesignTemperatureC");

                            b1.HasKey("ClimateZoneId");

                            b1.ToTable("ClimateZones");

                            b1.WithOwner()
                                .HasForeignKey("ClimateZoneId");
                        });

                    b.Navigation("SummerDesignTemperature")
                        .IsRequired();

                    b.Navigation("WinterDesignTemperature")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.HourlyClimateData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", "AnnualClimateData")
                        .WithMany("HourlyData")
                        .HasForeignKey("AnnualClimateDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", "ClimateData")
                        .WithMany("HourlyData")
                        .HasForeignKey("ClimateDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AnnualClimateData");

                    b.Navigation("ClimateData");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionLayer", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", "ConstructionAssembly")
                        .WithMany("Layers")
                        .HasForeignKey("ConstructionAssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Construction.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionAssembly");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", "Project")
                        .WithMany("Buildings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateZone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", "EquipmentSchedule")
                        .WithMany()
                        .HasForeignKey("EquipmentScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", "LightingSchedule")
                        .WithMany()
                        .HasForeignKey("LightingScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", "OccupancySchedule")
                        .WithMany()
                        .HasForeignKey("OccupancyScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Ventilation.VentilationParameters", "VentilationParameters")
                        .WithMany()
                        .HasForeignKey("VentilationParametersId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Power", "EquipmentLoad", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("EquipmentLoadW");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "IndoorTemperature", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("IndoorTemperatureC");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Power", "LightingLoad", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("LightingLoadW");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "OutdoorTemperatureOverride", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("OutdoorTemperatureOverrideC");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.Modules.Buildings.Domain.Ground.GroundContactMetadata", "GroundContactMetadata", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("BurialDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundBurialDepthM");

                            b1.Property<string>("ContactType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("GroundContactType");

                            b1.Property<double>("ExposedPerimeterM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundExposedPerimeterM");

                            b1.Property<double>("HorizontalInsulationWidthM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundHorizontalInsulationWidthM");

                            b1.Property<double>("PerimeterInsulationDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundPerimeterInsulationDepthM");

                            b1.Property<double>("UnderfloorVentilationAirChangesPerHour")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundUnderfloorVentilationAirChangesPerHour");

                            b1.Property<double>("WallHeightBelowGradeM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundWallHeightBelowGradeM");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("EquipmentLoad")
                        .IsRequired();

                    b.Navigation("EquipmentSchedule");

                    b.Navigation("Floor");

                    b.Navigation("GroundContactMetadata");

                    b.Navigation("IndoorTemperature")
                        .IsRequired();

                    b.Navigation("LightingLoad")
                        .IsRequired();

                    b.Navigation("LightingSchedule");

                    b.Navigation("OccupancySchedule");

                    b.Navigation("OutdoorTemperatureOverride");

                    b.Navigation("VentilationParameters");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Wall", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", "AdjacentRoom")
                        .WithMany()
                        .HasForeignKey("AdjacentRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", "ConstructionAssembly")
                        .WithMany()
                        .HasForeignKey("ConstructionAssemblyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", "Room")
                        .WithMany("Walls")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("WallId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.ThermalTransmittance", "UValue", b1 =>
                        {
                            b1.Property<int>("WallId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("UValue");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.Navigation("AdjacentRoom");

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("ConstructionAssembly");

                    b.Navigation("Room");

                    b.Navigation("UValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Window", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", "Room")
                        .WithMany("Windows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.ThermalTransmittance", "UValue", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("UValue");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.SolarHeatGainCoefficient", "Shgc", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("SHGC");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.WindowShadingParameters", "Shading", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("DiffuseSolarShareUnaffected")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingDiffuseSolarShareUnaffected");

                            b1.Property<double>("MinimumDirectSolarReductionFactor")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingMinimumDirectSolarReductionFactor");

                            b1.Property<double>("OverhangDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingOverhangDepthM");

                            b1.Property<double>("RevealDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingRevealDepthM");

                            b1.Property<double>("SideFinDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingSideFinDepthM");

                            b1.Property<double>("WindowHeightM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingWindowHeightM");

                            b1.Property<double>("WindowWidthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingWindowWidthM");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Shading")
                        .IsRequired();

                    b.Navigation("Shgc")
                        .IsRequired();

                    b.Navigation("UValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Settings.CalculationPreferences", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", "Project")
                        .WithOne("Preferences")
                        .HasForeignKey("AssistantEngineer.Modules.Buildings.Domain.Settings.CalculationPreferences", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.ThermalZones.ThermalZone", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", "Building")
                        .WithMany("ThermalZones")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Equipment.Domain.CoolingEquipmentCatalogItem", b =>
                {
                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Power", "NominalCoolingCapacity", b1 =>
                        {
                            b1.Property<int>("CoolingEquipmentCatalogItemId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("NominalCoolingCapacityW");

                            b1.HasKey("CoolingEquipmentCatalogItemId");

                            b1.ToTable("EquipmentCatalogItems");

                            b1.WithOwner()
                                .HasForeignKey("CoolingEquipmentCatalogItemId");
                        });

                    b.Navigation("NominalCoolingCapacity")
                        .IsRequired();
                });

            modelBuilder.Entity("ThermalZoneRooms", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.ThermalZones.ThermalZone", null)
                        .WithMany()
                        .HasForeignKey("ThermalZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", b =>
                {
                    b.Navigation("HourlyData");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", b =>
                {
                    b.Navigation("HourlyData");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("ThermalZones");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", b =>
                {
                    b.Navigation("Walls");

                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
