// <auto-generated />
using System;
using AssistantEngineer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistantEngineer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629165833_AddTelegramFileLibrary")]
    partial class AddTelegramFileLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId", "Year")
                        .IsUnique();

                    b.ToTable("AnnualClimateData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualHourlyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnualClimateDataId")
                        .HasColumnType("integer");

                    b.Property<int>("HourOfYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnnualClimateDataId", "HourOfYear")
                        .IsUnique();

                    b.ToTable("AnnualHourlyData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<double>("DailyTemperatureRange")
                        .HasColumnType("double precision");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId", "Month")
                        .IsUnique();

                    b.ToTable("ClimateData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ClimateZones", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.DesignDayHourlyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateDataId")
                        .HasColumnType("integer");

                    b.Property<int>("Hour")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateDataId", "Hour")
                        .IsUnique();

                    b.ToTable("DesignDayHourlyData", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ConstructionAssemblies", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionAssemblyId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<double>("ThicknessM")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionAssemblyId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ConstructionLayers", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DensityKgPerM3")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("SpecificHeatJPerKgK")
                        .HasColumnType("double precision");

                    b.Property<double>("ThermalConductivityWPerMK")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClimateZoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "Name")
                        .IsUnique();

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OrganizationId", "Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<double>("HeightM")
                        .HasColumnType("double precision");

                    b.Property<int?>("LightingScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OccupancyScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VentilationParametersId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentScheduleId");

                    b.HasIndex("LightingScheduleId");

                    b.HasIndex("OccupancyScheduleId");

                    b.HasIndex("VentilationParametersId");

                    b.HasIndex("FloorId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdjacentRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("BoundaryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ConstructionAssemblyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdjacentRoomId");

                    b.HasIndex("ConstructionAssemblyId");

                    b.HasIndex("RoomId");

                    b.ToTable("Walls", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Windows", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Factors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("HourlySchedules", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Settings.CalculationPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CoolingSafetyFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatingSafetyFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("Iso52016DefaultAirChangesPerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5);

                    b.Property<double>("Iso52016DiffuseSolarShareUnaffectedByShading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("Iso52016DirectSolarShadingReductionFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<double>("Iso52016InternalHeatCapacityJPerM2K")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(10000.0);

                    b.Property<double>("Iso52016SolarUtilizationFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.75);

                    b.Property<double>("Iso52016WindowFrameAreaFraction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.25);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CalculationPreferences", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.ThermalZones.ThermalZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("ThermalZones", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Ventilation.VentilationParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AirChangesPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatRecoveryEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("InfiltrationAirChangesPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("StackCoefficient")
                        .HasColumnType("double precision");

                    b.Property<double>("WindCoefficient")
                        .HasColumnType("double precision");

                    b.Property<double>("WindExposureFactor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("VentilationParameters", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Equipment.Domain.CoolingEquipmentCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "SystemType", "UnitType", "ModelName")
                        .IsUnique()
                        .HasDatabaseName("IX_EquipmentCatalogItems_CatalogIdentity");

                    b.ToTable("EquipmentCatalogItems", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Conversations.TelegramConversationSessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CandidateOptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastPromptMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("SelectedDisplayContext")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SelectedEquipmentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SelectedManufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("State");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("TelegramConversationSessions", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.History.TelegramDiagnosticCaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CandidateCount")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayContext")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedRequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PhoneNumberSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("PhoneWasSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResponseMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("TelegramConversationSessionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserRoleAtCreation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TelegramConversationSessionId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TelegramUserId", "CreatedAt");

                    b.ToTable("TelegramDiagnosticCases", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Manuals.TelegramLibraryAccessGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GrantedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByTelegramUserId");

                    b.HasIndex("TelegramUserId", "IsActive");

                    b.ToTable("TelegramLibraryAccessGrants", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Manuals.TelegramLibraryAccessRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RequestedRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Installer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ResolvedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Pending");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramChatId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TelegramUserId", "Status");

                    b.ToTable("TelegramLibraryAccessRequests", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Manuals.TelegramManualBindingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("CanUseForDiagnostics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("ServiceManual");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLibraryVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ManualId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("MinRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Engineer");

                    b.Property<string>("RegisteredByRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Series")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TelegramFileUniqueId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UploadedByTelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UploadedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ManualId");

                    b.HasIndex("Brand", "Series", "IsActive");

                    b.HasIndex("Brand", "Series", "DocumentType", "CanUseForDiagnostics", "IsActive");

                    b.ToTable("TelegramManualBindings", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.ServiceRequests.TelegramServiceRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("AssignedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AssignedTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContactPhoneLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiagnosticCaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayContext")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("NotificationChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NotificationMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NotificationUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumberSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("PhoneWasSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("StatusUpdatedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserRoleAtCreation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByTelegramUserId");

                    b.HasIndex("AssignedTelegramUserId");

                    b.HasIndex("DiagnosticCaseId")
                        .IsUnique()
                        .HasDatabaseName("IX_TelegramServiceRequests_ActiveDiagnosticCase")
                        .HasFilter("\"Status\" IN ('New', 'InProgress')");

                    b.HasIndex("Status");

                    b.HasIndex("StatusUpdatedByTelegramUserId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("DiagnosticCaseId", "Status");

                    b.HasIndex("TelegramUserId", "CreatedAt");

                    b.ToTable("TelegramServiceRequests", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.ServiceRequests.TelegramServiceRequestEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSuccessful")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("ServiceRequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetTelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TargetTelegramUserId");

                    b.HasIndex("ActorTelegramUserId", "CreatedAt");

                    b.HasIndex("EventType", "CreatedAt");

                    b.HasIndex("ServiceRequestId", "CreatedAt");

                    b.ToTable("TelegramServiceRequestEvents", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserAuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSuccessful")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<bool?>("NewIsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("NewIsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NewRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("OldIsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OldIsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OldRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("TargetTelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActorTelegramUserId", "CreatedAt");

                    b.HasIndex("CreatedAt", "Id");

                    b.HasIndex("EventType", "CreatedAt");

                    b.HasIndex("TargetTelegramUserId", "CreatedAt");

                    b.ToTable("TelegramUserAuditEvents", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastAccessDeniedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PhoneNumberSharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumberSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("PhoneNumberVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("IsEnabled", "IsBlocked");

                    b.ToTable("TelegramUsers", (string)null);
                });

            modelBuilder.Entity("ThermalZoneRooms", b =>
                {
                    b.Property<int>("ThermalZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("ThermalZoneId", "RoomId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("ThermalZoneRooms", (string)null);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClimateZone");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualHourlyData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", "AnnualClimateData")
                        .WithMany("HourlyData")
                        .HasForeignKey("AnnualClimateDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.Modules.Buildings.Domain.Climate.WeatherRecord", "Weather", b1 =>
                        {
                            b1.Property<int>("AnnualHourlyDataId")
                                .HasColumnType("integer");

                            b1.Property<double?>("AtmosphericPressurePa")
                                .HasColumnType("double precision")
                                .HasColumnName("AtmosphericPressurePa");

                            b1.Property<double>("DiffuseSolarRadiation")
                                .HasColumnType("double precision")
                                .HasColumnName("DiffuseSolarRadiation");

                            b1.Property<double>("DirectSolarRadiation")
                                .HasColumnType("double precision")
                                .HasColumnName("DirectSolarRadiation");

                            b1.Property<double>("DryBulbTemperature")
                                .HasColumnType("double precision")
                                .HasColumnName("DryBulbTemperature");

                            b1.Property<double?>("HorizontalInfraredRadiationWPerM2")
                                .HasColumnType("double precision")
                                .HasColumnName("HorizontalInfraredRadiationWPerM2");

                            b1.Property<double?>("OpaqueSkyCoverTenths")
                                .HasColumnType("double precision")
                                .HasColumnName("OpaqueSkyCoverTenths");

                            b1.Property<double?>("RelativeHumidityPercent")
                                .HasColumnType("double precision")
                                .HasColumnName("RelativeHumidityPercent");

                            b1.Property<double?>("SkyTemperatureC")
                                .HasColumnType("double precision")
                                .HasColumnName("SkyTemperatureC");

                            b1.Property<double?>("TotalSkyCoverTenths")
                                .HasColumnType("double precision")
                                .HasColumnName("TotalSkyCoverTenths");

                            b1.Property<double?>("WindDirectionDegrees")
                                .HasColumnType("double precision")
                                .HasColumnName("WindDirectionDegrees");

                            b1.Property<double?>("WindSpeedMPerS")
                                .HasColumnType("double precision")
                                .HasColumnName("WindSpeedMPerS");

                            b1.HasKey("AnnualHourlyDataId");

                            b1.ToTable("AnnualHourlyData");

                            b1.WithOwner()
                                .HasForeignKey("AnnualHourlyDataId");
                        });

                    b.Navigation("AnnualClimateData");

                    b.Navigation("Weather")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClimateZone");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", b =>
                {
                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "SummerDesignTemperature", b1 =>
                        {
                            b1.Property<int>("ClimateZoneId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("SummerDesignTemperatureC");

                            b1.HasKey("ClimateZoneId");

                            b1.ToTable("ClimateZones");

                            b1.WithOwner()
                                .HasForeignKey("ClimateZoneId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "WinterDesignTemperature", b1 =>
                        {
                            b1.Property<int>("ClimateZoneId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("WinterDesignTemperatureC");

                            b1.HasKey("ClimateZoneId");

                            b1.ToTable("ClimateZones");

                            b1.WithOwner()
                                .HasForeignKey("ClimateZoneId");
                        });

                    b.Navigation("SummerDesignTemperature")
                        .IsRequired();

                    b.Navigation("WinterDesignTemperature")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.DesignDayHourlyData", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", "ClimateData")
                        .WithMany("HourlyData")
                        .HasForeignKey("ClimateDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.Modules.Buildings.Domain.Climate.WeatherRecord", "Weather", b1 =>
                        {
                            b1.Property<int>("DesignDayHourlyDataId")
                                .HasColumnType("integer");

                            b1.Property<double?>("AtmosphericPressurePa")
                                .HasColumnType("double precision")
                                .HasColumnName("AtmosphericPressurePa");

                            b1.Property<double>("DiffuseSolarRadiation")
                                .HasColumnType("double precision")
                                .HasColumnName("DiffuseSolarRadiation");

                            b1.Property<double>("DirectSolarRadiation")
                                .HasColumnType("double precision")
                                .HasColumnName("DirectSolarRadiation");

                            b1.Property<double>("DryBulbTemperature")
                                .HasColumnType("double precision")
                                .HasColumnName("DryBulbTemperature");

                            b1.Property<double?>("HorizontalInfraredRadiationWPerM2")
                                .HasColumnType("double precision")
                                .HasColumnName("HorizontalInfraredRadiationWPerM2");

                            b1.Property<double?>("OpaqueSkyCoverTenths")
                                .HasColumnType("double precision")
                                .HasColumnName("OpaqueSkyCoverTenths");

                            b1.Property<double?>("RelativeHumidityPercent")
                                .HasColumnType("double precision")
                                .HasColumnName("RelativeHumidityPercent");

                            b1.Property<double?>("SkyTemperatureC")
                                .HasColumnType("double precision")
                                .HasColumnName("SkyTemperatureC");

                            b1.Property<double?>("TotalSkyCoverTenths")
                                .HasColumnType("double precision")
                                .HasColumnName("TotalSkyCoverTenths");

                            b1.Property<double?>("WindDirectionDegrees")
                                .HasColumnType("double precision")
                                .HasColumnName("WindDirectionDegrees");

                            b1.Property<double?>("WindSpeedMPerS")
                                .HasColumnType("double precision")
                                .HasColumnName("WindSpeedMPerS");

                            b1.HasKey("DesignDayHourlyDataId");

                            b1.ToTable("DesignDayHourlyData");

                            b1.WithOwner()
                                .HasForeignKey("DesignDayHourlyDataId");
                        });

                    b.Navigation("ClimateData");

                    b.Navigation("Weather")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionLayer", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", "ConstructionAssembly")
                        .WithMany("Layers")
                        .HasForeignKey("ConstructionAssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Construction.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionAssembly");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateZone", "ClimateZone")
                        .WithMany()
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", "Project")
                        .WithMany("Buildings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateZone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", "EquipmentSchedule")
                        .WithMany()
                        .HasForeignKey("EquipmentScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", "LightingSchedule")
                        .WithMany()
                        .HasForeignKey("LightingScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Schedules.HourlySchedule", "OccupancySchedule")
                        .WithMany()
                        .HasForeignKey("OccupancyScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Ventilation.VentilationParameters", "VentilationParameters")
                        .WithMany()
                        .HasForeignKey("VentilationParametersId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Power", "EquipmentLoad", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("EquipmentLoadW");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "IndoorTemperature", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("IndoorTemperatureC");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Power", "LightingLoad", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("LightingLoadW");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Temperature", "OutdoorTemperatureOverride", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("Celsius")
                                .HasColumnType("double precision")
                                .HasColumnName("OutdoorTemperatureOverrideC");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("AssistantEngineer.Modules.Buildings.Domain.Ground.GroundContactMetadata", "GroundContactMetadata", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<double>("BurialDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundBurialDepthM");

                            b1.Property<string>("ContactType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("GroundContactType");

                            b1.Property<double>("ExposedPerimeterM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundExposedPerimeterM");

                            b1.Property<double>("HorizontalInsulationWidthM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundHorizontalInsulationWidthM");

                            b1.Property<double>("PerimeterInsulationDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundPerimeterInsulationDepthM");

                            b1.Property<double>("UnderfloorVentilationAirChangesPerHour")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundUnderfloorVentilationAirChangesPerHour");

                            b1.Property<double>("WallHeightBelowGradeM")
                                .HasColumnType("double precision")
                                .HasColumnName("GroundWallHeightBelowGradeM");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("EquipmentLoad")
                        .IsRequired();

                    b.Navigation("EquipmentSchedule");

                    b.Navigation("Floor");

                    b.Navigation("GroundContactMetadata");

                    b.Navigation("IndoorTemperature")
                        .IsRequired();

                    b.Navigation("LightingLoad")
                        .IsRequired();

                    b.Navigation("LightingSchedule");

                    b.Navigation("OccupancySchedule");

                    b.Navigation("OutdoorTemperatureOverride");

                    b.Navigation("VentilationParameters");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Wall", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", "AdjacentRoom")
                        .WithMany()
                        .HasForeignKey("AdjacentRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", "ConstructionAssembly")
                        .WithMany()
                        .HasForeignKey("ConstructionAssemblyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", "Room")
                        .WithMany("Walls")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("WallId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.ThermalTransmittance", "UValue", b1 =>
                        {
                            b1.Property<int>("WallId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("UValue");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.Navigation("AdjacentRoom");

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("ConstructionAssembly");

                    b.Navigation("Room");

                    b.Navigation("UValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Window", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", "Room")
                        .WithMany("Windows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Area", "Area", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("SquareMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("AreaM2");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.ThermalTransmittance", "UValue", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("UValue");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.SolarHeatGainCoefficient", "Shgc", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("SHGC");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.WindowShadingParameters", "Shading", b1 =>
                        {
                            b1.Property<int>("WindowId")
                                .HasColumnType("integer");

                            b1.Property<double>("DiffuseSolarShareUnaffected")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingDiffuseSolarShareUnaffected");

                            b1.Property<double>("MinimumDirectSolarReductionFactor")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingMinimumDirectSolarReductionFactor");

                            b1.Property<double>("OverhangDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingOverhangDepthM");

                            b1.Property<double>("RevealDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingRevealDepthM");

                            b1.Property<double>("SideFinDepthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingSideFinDepthM");

                            b1.Property<double>("WindowHeightM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingWindowHeightM");

                            b1.Property<double>("WindowWidthM")
                                .HasColumnType("double precision")
                                .HasColumnName("ShadingWindowWidthM");

                            b1.HasKey("WindowId");

                            b1.ToTable("Windows");

                            b1.WithOwner()
                                .HasForeignKey("WindowId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Shading")
                        .IsRequired();

                    b.Navigation("Shgc")
                        .IsRequired();

                    b.Navigation("UValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Settings.CalculationPreferences", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", "Project")
                        .WithOne("Preferences")
                        .HasForeignKey("AssistantEngineer.Modules.Buildings.Domain.Settings.CalculationPreferences", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.ThermalZones.ThermalZone", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", "Building")
                        .WithMany("ThermalZones")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Equipment.Domain.CoolingEquipmentCatalogItem", b =>
                {
                    b.OwnsOne("AssistantEngineer.SharedKernel.ValueObjects.Power", "NominalCoolingCapacity", b1 =>
                        {
                            b1.Property<int>("CoolingEquipmentCatalogItemId")
                                .HasColumnType("integer");

                            b1.Property<double>("Watts")
                                .HasColumnType("double precision")
                                .HasColumnName("NominalCoolingCapacityW");

                            b1.HasKey("CoolingEquipmentCatalogItemId");

                            b1.ToTable("EquipmentCatalogItems");

                            b1.WithOwner()
                                .HasForeignKey("CoolingEquipmentCatalogItemId");
                        });

                    b.Navigation("NominalCoolingCapacity")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Conversations.TelegramConversationSessionEntity", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.History.TelegramDiagnosticCaseEntity", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Conversations.TelegramConversationSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("TelegramConversationSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.ServiceRequests.TelegramServiceRequestEntity", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedByTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.History.TelegramDiagnosticCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("StatusUpdatedByTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.ServiceRequests.TelegramServiceRequestEventEntity", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.ServiceRequests.TelegramServiceRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserAuditEventEntity", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssistantEngineer.Modules.EquipmentDiagnostics.Application.Telegram.Users.TelegramUserEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ThermalZoneRooms", b =>
                {
                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantEngineer.Modules.Buildings.Domain.ThermalZones.ThermalZone", null)
                        .WithMany()
                        .HasForeignKey("ThermalZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.AnnualClimateData", b =>
                {
                    b.Navigation("HourlyData");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Climate.ClimateData", b =>
                {
                    b.Navigation("HourlyData");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Construction.ConstructionAssembly", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Building", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("ThermalZones");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Project", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("AssistantEngineer.Modules.Buildings.Domain.Entities.Room", b =>
                {
                    b.Navigation("Walls");

                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
