@host = http://localhost:5218

### Получить все помещения
GET {{host}}/api/room
Accept: application/json

### Получить помещение по id
GET {{host}}/api/room/1
Accept: application/json

### Создать помещение 1 — кабинет
POST {{host}}/api/room
Content-Type: application/json
Accept: application/json

{
  "name": "Office 101",
  "areaM2": 24,
  "heightM": 3.0,
  "indoorTemperatureC": 24,
  "outdoorTemperatureC": 38
}

### Создать помещение 2 — переговорная
POST {{host}}/api/room
Content-Type: application/json
Accept: application/json

{
  "name": "Meeting Room",
  "areaM2": 42,
  "heightM": 3.2,
  "indoorTemperatureC": 23,
  "outdoorTemperatureC": 36
}

### Создать помещение 3 — серверная
POST {{host}}/api/room
Content-Type: application/json
Accept: application/json

{
  "name": "Server Room",
  "areaM2": 18,
  "heightM": 3.0,
  "indoorTemperatureC": 20,
  "outdoorTemperatureC": 40
}

### Рассчитать тепловую нагрузку для помещения 1
GET {{host}}/api/room/1/calculate
Accept: application/json

### Рассчитать тепловую нагрузку для помещения 2
GET {{host}}/api/room/2/calculate
Accept: application/json

### Добавить окно 1
POST http://localhost:5218/api/room/1/windows
Content-Type: application/json
Accept: application/json

{
  "areaM2": 3.2
}

### Добавить окно 2
POST http://localhost:5218/api/room/1/windows
Content-Type: application/json
Accept: application/json

{
  "areaM2": 5.2
}

### Получить все окна
GET http://localhost:5218/api/room/1/windows
Accept: application/json

### Добавить стену
POST http://localhost:5218/api/room/1/walls
Content-Type: application/json
Accept: application/json

{
  "areaM2": 12.5,
  "isExternal": true
}

###Получить стены комнаты
GET http://localhost:5218/api/room/1/walls
Accept: application/json